### PR TITLE
Improvements to the segmentation tutorial

### PR DESCRIPTION
**Pull request by jni**
- gentler introduction to napari, including an exercise
- Use Farid filter
- Better explanation of why we use morphology
- Remove advanced examples (move to later optional lessons)
- comment out points setting

### CODE REVIEW

**Review by kne42 — APPROVED** [review]
<cannot do a real review on mobile anymore RIP>

L89: is it necessary to say killer app? 😂
L104: nit: why do some bullet entries start with a capitalized words and the others do not?

**Comment by kne42** [comment]
also feel free to ignore but L146 i think `imshow` is more confusing than using `view_image` and getting the layers from `viewer.layers`

**Comment by jni** [comment]
@kne42 `view_*` is getting deprecated so... LOL

**Comment by kne42** [comment]
oopsies 😅

**Pull request merged**
